name: Playwright

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy
      options: --add-host gitea:host-gateway --add-host host.docker.internal:host-gateway --mount type=volume,source=playwright-npm-cache,target=/root/.npm
    env:
      APP_URL: http://host.docker.internal:8000
      BASE_URL: http://host.docker.internal:8000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          github-server-url: http://gitea:3000

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run Playwright tests
        run: npx playwright test
