import { GeneratorOptions } from '../types.js';

export function generateGiteaWorkflow(opts: GeneratorOptions): string {
  const { gitea } = opts;
  const containerOptionsParts = [
    `--add-host gitea:host-gateway`,
    `--add-host host.docker.internal:host-gateway`,
    `--mount type=volume,source=${gitea.npmCacheVolume},target=/root/.npm`,
  ];
  const containerOptions = containerOptionsParts.join(' ');

  return [
    `name: Playwright`,
    ``,
    `on:`,
    `  workflow_dispatch:`,
    `  push:`,
    `    branches:`,
    `      - ${gitea.branch}`,
    ``,
    `jobs:`,
    `  playwright:`,
    `    runs-on: ubuntu-latest`,
    `    container:`,
    `      image: ${gitea.playwrightImage}`,
    `      options: ${containerOptions}`,
    `    env:`,
    `      APP_URL: http://${gitea.appHost}`,
    `      BASE_URL: http://${gitea.appHost}`,
    `      PLAYWRIGHT_DIR: playwright`,
    `    steps:`,
    `      - name: Checkout repository`,
    `        uses: actions/checkout@v4`,
    `        with:`,
    `          github-server-url: ${gitea.serverUrl}`,
    ``,
    `      - name: Install dependencies`,
    `        run: |`,
    `          if [ ! -f "$PLAYWRIGHT_DIR/package.json" ]; then`,
    `            echo "Missing $PLAYWRIGHT_DIR/package.json"`,
    `            exit 1`,
    `          fi`,
    `          cd "$PLAYWRIGHT_DIR"`,
    `          npm install --prefer-offline --no-audit --no-fund`,
    ``,
    `      - name: Run Playwright tests`,
    `        run: |`,
    `          cd "$PLAYWRIGHT_DIR"`,
    `          npx playwright test`,
    ``,
    `      - name: Save report to branch folder`,
    `        if: always() && github.actor != 'gitea-actions[bot]'`,
    `        run: |`,
    `          if [ ! -d "$PLAYWRIGHT_DIR/playwright-report" ] && [ ! -f "$PLAYWRIGHT_DIR/playwright-report.json" ]; then`,
    `            echo "No Playwright report output found, skipping publish"`,
    `            exit 0`,
    `          fi`,
    ``,
    `          REPORT_DIR="$PLAYWRIGHT_DIR/reports"`,
    `          rm -rf "$REPORT_DIR"`,
    `          mkdir -p "$REPORT_DIR"`,
    `          if [ -d "$PLAYWRIGHT_DIR/playwright-report" ]; then cp -r "$PLAYWRIGHT_DIR/playwright-report"/. "$REPORT_DIR"/; fi`,
    `          if [ -f "$PLAYWRIGHT_DIR/playwright-report/report.json" ]; then cp "$PLAYWRIGHT_DIR/playwright-report/report.json" "$REPORT_DIR/report.json"; fi`,
    `          if [ -f "$PLAYWRIGHT_DIR/playwright-report.json" ] && [ ! -f "$REPORT_DIR/report.json" ]; then cp "$PLAYWRIGHT_DIR/playwright-report.json" "$REPORT_DIR/report.json"; fi`,
    ``,
    `          git config user.name "gitea-actions[bot]"`,
    `          git config user.email "gitea-actions@localhost"`,
    `          git add "$REPORT_DIR"`,
    `          git commit -m "test(playwright): generate report" || echo "No report changes to commit"`,
    `          git push origin "HEAD:${gitea.branch}"`,
  ].join('\n') + '\n';
}
