<?php

namespace App\Livewire;

use Carbon\Carbon;
use Illuminate\Support\Facades\File;
use Livewire\Component;

/**
 * Livewire component responsible for displaying and parsing the live execution logs of a test.
 * Reads the local log file generated by the background processes and constructs a visual
 * progress timeline by applying regex markers against the raw text.
 */
class TestLog extends Component
{
    /**
     * Defines the sequential stages of test generation and execution.
     * Each stage is identified in the logs by a specific 'marker' string.
     *
     * @var array<int, array{key: string, label: string, marker: string}>
     */
    private const TIMELINE_STAGES = [
        [
            'key' => 'provisioning',
            'label' => 'Provisioning',
            'marker' => 'Starting generator process',
            'subtasks' => [
                ['label' => 'Setup Workspace', 'marker' => 'Starting generator process'],
                ['label' => 'Stage Environment', 'marker' => 'Cloning source from'],
                ['label' => 'Deploy Application', 'marker' => 'Starting Playwright tests on Gitea Actions run'],
            ]
        ],
        [
            'key' => 'discovery',
            'label' => 'Discovery',
            'marker' => 'Discovering guest routes',
            'subtasks' => [
                ['label' => 'Scan Guest Routes', 'marker' => 'Discovering guest routes'],
                ['label' => 'Generate Guest Data', 'marker' => 'Extracting guest route'],
                ['label' => 'Authenticate Session', 'marker' => 'Authenticating session'],
                ['label' => 'Scan Auth Routes', 'marker' => 'Discovering auth routes'],
                ['label' => 'Generate Auth Data', 'marker' => 'Extracting auth route'],
                ['label' => 'Analyze Crawl Data', 'marker' => 'Analysing dataset'],
            ]
        ],
        [
            'key' => 'generation',
            'label' => 'Generation',
            'marker' => 'Generating Page Objects',
            'subtasks' => [
                ['label' => 'Build Page Objects', 'marker' => 'Generating Page Objects'],
                ['label' => 'Build Test Specs', 'marker' => 'Generating Test Specs'],
                ['label' => 'Build Configuration', 'marker' => 'Generating Playwright Configuration'],
            ]
        ],
        [
            'key' => 'execution',
            'label' => 'Execution',
            'marker' => 'tests using ',
            'subtasks' => [
                ['label' => 'Run Playwright Tests', 'marker' => 'tests using '],
            ]
        ],
        [
            'key' => 'feedback',
            'label' => 'Feedback',
            'marker' => 'Playwright report available',
            'subtasks' => [
                ['label' => 'Publish Report', 'marker' => 'Playwright report available'],
                ['label' => 'Teardown Workspace', 'marker' => 'Done'],
            ]
        ],
    ];

    /**
     * Common strings outputted during fatal errors.
     * Finding these indicates the process halted abnormally.
     *
     * @var array<int, string>
     */
    private const FAILURE_MARKERS = [
        'Git Clone Error',
        'Error running [',
        'Error:',
        'Exception:',
    ];

    /**
     * Markers indicating the user manually aborted the generation.
     *
     * @var array<int, string>
     */
    private const CANCELLATION_MARKERS = [
        'Generation cancelled by user.',
    ];
    /** The target test ID. */
    public int $testId;

    /** Display mode for the UI (e.g., 'both', 'logs', 'timeline'). */
    public string $viewType = 'both';

    public function mount(int $testId, string $viewType = 'both')
    {
        $this->testId = $testId;
        $this->viewType = $viewType;
    }

    /**
     * Reads the raw local log file.
     * Returns a placeholder message if the file doesn't exist yet.
     */
    public function getLogsProperty(): string
    {
        $path = config('filesystems.locida.paths.logs');
        $logFile = storage_path("{$path}/test-{$this->testId}.log");

        if (!File::exists($logFile)) {
            return "Waiting for generator to start\n";
        }

        return File::get($logFile);
    }

    /**
     * Cleans up the raw logs for terminal-like display in the browser.
     * Removes excessive blank lines and trailing whitespace.
     */
    public function getFormattedLogsProperty(): string
    {
        $logs = str_replace(["\r\n", "\r"], "\n", $this->logs);

        // Keep logs readable by removing trailing spaces and excessive blank lines.
        $logs = preg_replace('/[ \t]+$/m', '', $logs) ?? $logs;
        $logs = preg_replace("/\n{3,}/", "\n\n", $logs) ?? $logs;

        return rtrim($logs, "\n") . "\n";
    }

    /**
     * Analyzes the raw logs against known string markers to determine
     * the current phase of the process, success/failure status, and calculates
     * duration timestamps for each completed stage.
     *
     * @return array{isWaiting: bool, stages: array<int, array{key: string, label: string, status: string, duration?: string}>}
     */
    public function getTimelineProperty(): array
    {
        $logs = $this->logs;
        $isWaiting = str_starts_with($logs, 'Waiting for generator to start');

        if ($isWaiting) {
            return [
                'isWaiting' => true,
                'stages' => array_map(static fn (array $stage): array => [
                    'key' => $stage['key'],
                    'label' => $stage['label'],
                    'description' => $stage['description'] ?? '',
                    'status' => 'pending',
                    'subtasks' => array_map(static fn (array $st): array => [
                        'label' => $st['label'],
                        'status' => 'pending',
                        'marker' => $st['marker']
                    ], $stage['subtasks'] ?? []),
                ], self::TIMELINE_STAGES),
            ];
        }

        // 1. Identify which stages have been reached by searching for markers
        $stagePositions = [];
        foreach (self::TIMELINE_STAGES as $stage) {
            $position = strpos($logs, $stage['marker']);
            if ($position !== false) {
                $stagePositions[$stage['key']] = $position;
            }
        }

        // 2. Identify if and where a fatal failure occurred
        $failurePosition = null;
        foreach (self::FAILURE_MARKERS as $marker) {
            $position = strpos($logs, $marker);
            if ($position === false) {
                continue;
            }

            $failurePosition = $failurePosition === null
                ? $position
                : min($failurePosition, $position);
        }

        // 3. Identify if and where a cancellation occurred
        $cancellationPosition = null;
        foreach (self::CANCELLATION_MARKERS as $marker) {
            $position = strpos($logs, $marker);
            if ($position === false) {
                continue;
            }

            $cancellationPosition = $cancellationPosition === null
                ? $position
                : min($cancellationPosition, $position);
        }

        $activeStageKey = null;
        $completedStageKey = null;

        if (strpos($logs, '] Done') !== false || strpos($logs, "\nDone\n") !== false) {
            $completedStageKey = 'done';
        } else {
            // Find the most recently triggered stage
            foreach (array_reverse(self::TIMELINE_STAGES) as $stage) {
                if (isset($stagePositions[$stage['key']])) {
                    $activeStageKey = $stage['key'];
                    break;
                }
            }

            if ($activeStageKey === null) {
                $activeStageKey = 'setup';
            }
        }

        $stages = [];
        $failedAttached = false;

        // 4. Map the positions into stateful statuses for the UI (done, active, failed, cancelled, pending)
        foreach (self::TIMELINE_STAGES as $index => $stage) {
            $status = 'pending';
            $stagePosition = $stagePositions[$stage['key']] ?? null;

            if ($completedStageKey !== null) {
                $status = 'done';
            } elseif ($cancellationPosition !== null) {
                if ($stagePosition !== null && $stagePosition < $cancellationPosition) {
                    $status = 'done';
                }

                if ($stage['key'] === $activeStageKey) {
                    $status = 'cancelled';
                    $failedAttached = true;
                }
            } elseif ($failurePosition !== null) {
                if ($stagePosition !== null && $stagePosition < $failurePosition) {
                    $status = 'done';
                }

                if ($stage['key'] === $activeStageKey) {
                    $status = 'failed';
                    $failedAttached = true;
                }
            } else {
                if ($stage['key'] === $activeStageKey) {
                    $status = 'active';
                } elseif ($stagePosition !== null) {
                    $status = 'done';
                }
            }

            $stageSubtasks = [];
            $subtasks = $stage['subtasks'] ?? [];
            foreach ($subtasks as $idx => $subtask) {
                $subStatus = 'pending';
                $subPosition = strpos($logs, $subtask['marker']);
                $nextSubtask = $subtasks[$idx + 1] ?? null;
                $nextSubPosition = $nextSubtask ? strpos($logs, $nextSubtask['marker']) : false;
                
                if ($status === 'done') {
                    $subStatus = 'done';
                } elseif ($status === 'failed' || $status === 'cancelled') {
                     $terminalPos = $failurePosition ?? $cancellationPosition ?? PHP_INT_MAX;
                     if ($subPosition !== false && $subPosition < $terminalPos) {
                         if ($nextSubPosition !== false && $nextSubPosition < $terminalPos) {
                             $subStatus = 'done';
                         } else {
                             $subStatus = $status;
                         }
                     }
                } else {
                     if ($subPosition !== false) {
                         if ($nextSubPosition !== false) {
                             $subStatus = 'done';
                         } else {
                             $subStatus = 'active';
                         }
                     }
                }
                
                $stageSubtasks[] = [
                    'label' => $subtask['label'],
                    'status' => $subStatus,
                    'marker' => $subtask['marker'],
                ];
            }

            // if stage is active, make the first 'pending' subtask 'active'
            if ($status === 'active') {
                $hasActive = false;
                foreach ($stageSubtasks as $idx => $st) {
                     if ($st['status'] === 'done' || $st['status'] === 'active') {
                         if ($st['status'] === 'active') {
                             $hasActive = true;
                         }
                         continue;
                     }
                     if (!$hasActive) {
                         $stageSubtasks[$idx]['status'] = 'active';
                         $hasActive = true;
                     }
                }
            }

            $stages[] = [
                'key' => $stage['key'],
                'label' => $stage['label'],
                'description' => $stage['description'] ?? '',
                'status' => $status,
                'subtasks' => $stageSubtasks,
            ];
        }

        // Ensure failure/cancellation isn't lost if it happened before the first stage marker
        if (($failurePosition !== null || $cancellationPosition !== null) && ! $failedAttached) {
            $lastStageIndex = count($stages) - 1;
            if ($lastStageIndex >= 0) {
                $stages[$lastStageIndex]['status'] = $cancellationPosition !== null ? 'cancelled' : 'failed';
            }
        }

        // 5. Extract timestamps for each marker using Regex to calculate phase duration
        $stageTimestamps = [];
        foreach (self::TIMELINE_STAGES as $s) {
            $marker = preg_quote($s['marker'], '/');
            // Matches formats like [2026-06-06 12:00:00] or ISO8601
            $pattern = '/(?:\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]|(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.\d+)?Z)[^\n]*?' . $marker . '/';
            if (preg_match($pattern, $logs, $matches)) {
                if (!empty($matches[1])) {
                    $stageTimestamps[$s['key']] = Carbon::createFromFormat('Y-m-d H:i:s', $matches[1]);
                } elseif (!empty($matches[2])) {
                    $stageTimestamps[$s['key']] = Carbon::createFromFormat('Y-m-d H:i:s', str_replace('T', ' ', $matches[2]), 'UTC')->setTimezone(config('app.timezone', 'UTC'));
                }
            }
        }

        // 6. Find the last timestamp in the entire log to use for ongoing stages
        $lastLogTimestamp = null;
        $pattern = '/(?:\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]|(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.\d+)?Z)/';
        if (preg_match_all($pattern, $logs, $matches)) {
            $lastTimestampStr1 = end($matches[1]);
            $lastTimestampStr2 = end($matches[2]);
            if (!empty($lastTimestampStr1)) {
                $lastLogTimestamp = Carbon::createFromFormat('Y-m-d H:i:s', $lastTimestampStr1);
            } elseif (!empty($lastTimestampStr2)) {
                $lastLogTimestamp = Carbon::createFromFormat('Y-m-d H:i:s', str_replace('T', ' ', $lastTimestampStr2), 'UTC')->setTimezone(config('app.timezone', 'UTC'));
            }
        }
        $virtualNow = now();
        if ($lastLogTimestamp) {
            $path = config('filesystems.locida.paths.logs');
            $logFile = storage_path("{$path}/test-{$this->testId}.log");
            if (File::exists($logFile)) {
                $lastModified = Carbon::createFromTimestamp(File::lastModified($logFile));
                $skew = $lastModified->diffInSeconds($lastLogTimestamp, false);
                $virtualNow = now()->addSeconds($skew);
            } else {
                $virtualNow = $lastLogTimestamp;
            }
        }

        // 7. Calculate durations between timestamps
        for ($i = 0; $i < count($stages); $i++) {
            $currentKey = $stages[$i]['key'];
            $nextKey = $stages[$i + 1]['key'] ?? null;
            $start = $stageTimestamps[$currentKey] ?? null;
            $end = $stageTimestamps[$nextKey] ?? null;
            $durationStr = '';

            if ($start) {
                if ($end) {
                    $duration = max(0, $start->diffInSeconds($end));
                } elseif ($stages[$i]['status'] === 'active') {
                    $duration = max(0, $start->diffInSeconds($virtualNow));
                } elseif (in_array($stages[$i]['status'], ['failed', 'cancelled', 'done'])) {
                    $duration = max(0, $start->diffInSeconds($lastLogTimestamp ?? $virtualNow));
                } else {
                    $duration = null;
                }

                if ($duration !== null) {
                    $duration = (int) round($duration);
                    if ($duration >= 60) {
                        $m = (int) floor($duration / 60);
                        $s = $duration % 60;
                        $durationStr = "{$m}m {$s}s";
                    } else {
                        $durationStr = "{$duration}s";
                    }
                }
            }
            $stages[$i]['duration'] = $durationStr;
        }

        // 8. Filter out synthetic start/done milestones for UI presentation
        $filteredStages = array_values(array_filter($stages, function ($s) {
            return !in_array($s['key'], ['start', 'done']);
        }));

        return [
            'isWaiting' => false,
            'stages' => $filteredStages,
        ];
    }

    public function render()
    {
        return view('livewire.test-log');
    }
}
