<?php

namespace App\Livewire;

use Carbon\Carbon;
use Illuminate\Support\Facades\File;
use Livewire\Component;

/**
 * Livewire component responsible for displaying and parsing the live execution logs of a test.
 * Reads the local log file generated by the background processes and constructs a visual
 * progress timeline by applying regex markers against the raw text.
 */
class TestLog extends Component
{
    /**
     * Defines the sequential stages of test generation and execution.
     * Each stage is identified in the logs by a specific 'marker' string.
     *
     * @var array<int, array{key: string, label: string, marker: string}>
     */
    private const TIMELINE_STAGES = [
        ['key' => 'start', 'label' => 'Start', 'marker' => 'Starting generator process'],
        ['key' => 'init', 'label' => 'Test Initialization', 'marker' => 'Cloning source'],
        ['key' => 'generate', 'label' => 'Test Generation', 'marker' => 'Discovering guest routes'],
        ['key' => 'execute', 'label' => 'Test Execution', 'marker' => 'tests using '],
        ['key' => 'report', 'label' => 'Test Reporting', 'marker' => 'Playwright report available'],
        ['key' => 'done', 'label' => 'Completed', 'marker' => 'Done.'],
    ];

    /**
     * Common strings outputted during fatal errors.
     * Finding these indicates the process halted abnormally.
     *
     * @var array<int, string>
     */
    private const FAILURE_MARKERS = [
        'Git Clone Error',
        'Error running [',
        'Error:',
        'Exception:',
    ];

    /**
     * Markers indicating the user manually aborted the generation.
     *
     * @var array<int, string>
     */
    private const CANCELLATION_MARKERS = [
        'Generation cancelled by user.',
    ];
    /** The target test ID. */
    public int $testId;

    /** Display mode for the UI (e.g., 'both', 'logs', 'timeline'). */
    public string $viewType = 'both';

    public function mount(int $testId, string $viewType = 'both')
    {
        $this->testId = $testId;
        $this->viewType = $viewType;
    }

    /**
     * Reads the raw local log file.
     * Returns a placeholder message if the file doesn't exist yet.
     */
    public function getLogsProperty(): string
    {
        $logFile = storage_path("app/generator-logs/test-{$this->testId}.log");

        if (!File::exists($logFile)) {
            return "Waiting for generator to start...\n";
        }

        return File::get($logFile);
    }

    /**
     * Cleans up the raw logs for terminal-like display in the browser.
     * Removes excessive blank lines and trailing whitespace.
     */
    public function getFormattedLogsProperty(): string
    {
        $logs = str_replace(["\r\n", "\r"], "\n", $this->logs);

        // Keep logs readable by removing trailing spaces and excessive blank lines.
        $logs = preg_replace('/[ \t]+$/m', '', $logs) ?? $logs;
        $logs = preg_replace("/\n{3,}/", "\n\n", $logs) ?? $logs;

        return rtrim($logs, "\n") . "\n";
    }

    /**
     * Analyzes the raw logs against known string markers to determine
     * the current phase of the process, success/failure status, and calculates
     * duration timestamps for each completed stage.
     *
     * @return array{isWaiting: bool, stages: array<int, array{key: string, label: string, status: string, duration?: string}>}
     */
    public function getTimelineProperty(): array
    {
        $logs = $this->logs;
        $isWaiting = str_starts_with($logs, 'Waiting for generator to start');

        if ($isWaiting) {
            return [
                'isWaiting' => true,
                'stages' => array_map(static fn (array $stage): array => [
                    'key' => $stage['key'],
                    'label' => $stage['label'],
                    'status' => 'pending',
                ], self::TIMELINE_STAGES),
            ];
        }

        // 1. Identify which stages have been reached by searching for markers
        $stagePositions = [];
        foreach (self::TIMELINE_STAGES as $stage) {
            $position = strpos($logs, $stage['marker']);
            if ($position !== false) {
                $stagePositions[$stage['key']] = $position;
            }
        }

        // 2. Identify if and where a fatal failure occurred
        $failurePosition = null;
        foreach (self::FAILURE_MARKERS as $marker) {
            $position = strpos($logs, $marker);
            if ($position === false) {
                continue;
            }

            $failurePosition = $failurePosition === null
                ? $position
                : min($failurePosition, $position);
        }

        // 3. Identify if and where a cancellation occurred
        $cancellationPosition = null;
        foreach (self::CANCELLATION_MARKERS as $marker) {
            $position = strpos($logs, $marker);
            if ($position === false) {
                continue;
            }

            $cancellationPosition = $cancellationPosition === null
                ? $position
                : min($cancellationPosition, $position);
        }

        $activeStageKey = null;
        $completedStageKey = null;

        if (isset($stagePositions['done'])) {
            $completedStageKey = 'done';
        } else {
            // Find the most recently triggered stage
            foreach (array_reverse(self::TIMELINE_STAGES) as $stage) {
                if (isset($stagePositions[$stage['key']])) {
                    $activeStageKey = $stage['key'];
                    break;
                }
            }

            if ($activeStageKey === null) {
                $activeStageKey = 'start';
            }
        }

        $stages = [];
        $failedAttached = false;

        // 4. Map the positions into stateful statuses for the UI (done, active, failed, cancelled, pending)
        foreach (self::TIMELINE_STAGES as $index => $stage) {
            $status = 'pending';
            $stagePosition = $stagePositions[$stage['key']] ?? null;

            if ($completedStageKey !== null) {
                $status = 'done';
            } elseif ($cancellationPosition !== null) {
                if ($stagePosition !== null && $stagePosition < $cancellationPosition) {
                    $status = 'done';
                }

                if ($stage['key'] === $activeStageKey) {
                    $status = 'cancelled';
                    $failedAttached = true;
                }
            } elseif ($failurePosition !== null) {
                if ($stagePosition !== null && $stagePosition < $failurePosition) {
                    $status = 'done';
                }

                if ($stage['key'] === $activeStageKey) {
                    $status = 'failed';
                    $failedAttached = true;
                }
            } else {
                if ($stage['key'] === $activeStageKey) {
                    $status = 'active';
                } elseif ($stagePosition !== null) {
                    $status = 'done';
                }
            }

            $stages[] = [
                'key' => $stage['key'],
                'label' => $stage['label'],
                'status' => $status,
            ];
        }

        // Ensure failure/cancellation isn't lost if it happened before the first stage marker
        if (($failurePosition !== null || $cancellationPosition !== null) && ! $failedAttached) {
            $lastStageIndex = count($stages) - 1;
            if ($lastStageIndex >= 0) {
                $stages[$lastStageIndex]['status'] = $cancellationPosition !== null ? 'cancelled' : 'failed';
            }
        }

        // 5. Extract timestamps for each marker using Regex to calculate phase duration
        $stageTimestamps = [];
        foreach (self::TIMELINE_STAGES as $s) {
            $marker = preg_quote($s['marker'], '/');
            // Matches formats like [2026-06-06 12:00:00] or ISO8601
            $pattern = '/(?:\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]|(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.\d+)?Z)[^\n]*?' . $marker . '/';
            if (preg_match($pattern, $logs, $matches)) {
                if (!empty($matches[1])) {
                    $stageTimestamps[$s['key']] = Carbon::createFromFormat('Y-m-d H:i:s', $matches[1]);
                } elseif (!empty($matches[2])) {
                    $stageTimestamps[$s['key']] = Carbon::createFromFormat('Y-m-d H:i:s', str_replace('T', ' ', $matches[2]), 'UTC')->setTimezone(config('app.timezone', 'UTC'));
                }
            }
        }

        // 6. Calculate durations between timestamps
        for ($i = 0; $i < count($stages); $i++) {
            $currentKey = $stages[$i]['key'];
            $nextKey = $stages[$i + 1]['key'] ?? null;
            $start = $stageTimestamps[$currentKey] ?? null;
            $end = $stageTimestamps[$nextKey] ?? null;
            $durationStr = '';

            if ($start) {
                if ($end) {
                    $duration = max(0, $start->diffInSeconds($end));
                } elseif ($stages[$i]['status'] === 'active') {
                    $duration = max(0, $start->diffInSeconds(now()));
                } elseif ($stages[$i]['status'] === 'failed') {
                    $logFile = storage_path("app/generator-logs/test-{$this->testId}.log");
                    if (File::exists($logFile)) {
                        $duration = max(0, $start->diffInSeconds(Carbon::createFromTimestamp(File::lastModified($logFile))));
                    } else {
                        $duration = null;
                    }
                } else {
                    $duration = null;
                }

                if ($duration !== null) {
                    if ($duration >= 60) {
                        $m = floor($duration / 60);
                        $s = $duration % 60;
                        $durationStr = "{$m}m {$s}s";
                    } else {
                        $durationStr = "{$duration}s";
                    }
                }
            }
            $stages[$i]['duration'] = $durationStr;
        }

        // 7. Filter out synthetic start/done milestones for UI presentation
        $filteredStages = array_values(array_filter($stages, function ($s) {
            return !in_array($s['key'], ['start', 'done']);
        }));

        return [
            'isWaiting' => false,
            'stages' => $filteredStages,
        ];
    }

    public function render()
    {
        return view('livewire.test-log');
    }
}
